name:                spotto-bot
version:             0.1.0.0
github:              "taylandogan/spotto-bot"
license:             BSD3
author:              "Taylan Dogan"
maintainer:          "ttaylan.dogann@gmail.com"
copyright:           "2020 Taylan Dogan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/taylandogan/spotto-bot#readme>

dependencies:
- aeson
- aeson-lens
- base >= 4.7 && < 5
- lens
- wreq

library:
  source-dirs: src

executables:
  spotto-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spotto-bot

tests:
  spotto-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spotto-bot
